# Generated by Django 2.2.4 on 2019-09-03 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadBatches',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.CharField(max_length=15)),
                ('created_timestamp', models.DateTimeField(auto_now_add=True)),
                ('modified_by', models.CharField(max_length=15)),
                ('batch_name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Collection Batch',
                'verbose_name_plural': 'Collection Batches',
            },
        ),
        migrations.CreateModel(
            name='Observations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.CharField(max_length=15)),
                ('created_timestamp', models.DateTimeField(auto_now_add=True)),
                ('modified_by', models.CharField(max_length=15)),
                ('observation_name', models.CharField(max_length=20)),
                ('lattitude', models.DecimalField(decimal_places=8, max_digits=11, null=True)),
                ('longitude', models.DecimalField(decimal_places=8, max_digits=11, null=True)),
                ('gps_datum', models.CharField(max_length=10, null=True)),
                ('Text1', models.CharField(max_length=50, null=True)),
                ('Text2', models.CharField(max_length=50, null=True)),
                ('Text3', models.CharField(max_length=50, null=True)),
                ('Int1', models.IntegerField(null=True)),
                ('Int2', models.IntegerField(null=True)),
                ('Int3', models.IntegerField(null=True)),
                ('notes', models.TextField(null=True)),
                ('upload_batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.UploadBatches')),
            ],
            options={
                'verbose_name': 'Observation',
                'verbose_name_plural': 'Observations',
            },
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.CharField(max_length=15)),
                ('created_timestamp', models.DateTimeField(auto_now_add=True)),
                ('modified_by', models.CharField(max_length=15)),
                ('image_name', models.CharField(max_length=50)),
                ('observation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Observations')),
            ],
            options={
                'verbose_name': 'Image',
                'verbose_name_plural': 'Images',
            },
        ),
    ]
